apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-config
data:
  APP_BASE_URL: "http://joplin.local"
  APP_PORT: "80"
  DB_CLIENT: "pg"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "joplin"
  POSTGRES_USER: "joplin"
  POSTGRES_PASSWORD: "ChangePassword"
  SQLITE_DATABASE: "/data/db.sqlite"
# PUID: "1000"
# PGID: "1000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin
  labels:
    app: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin
  template:
    metadata:
      labels:
        app: joplin
    spec:
      containers:
      - name: joplin
        image: redrathnure/joplin
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: joplin-config
---
apiVersion: v1
kind: Service
metadata:
  name: joplin
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: joplin
